"""add resend mail provider config

Revision ID: 0bff0ee5acf3
Revises: 1953f2994a49
Create Date: 2026-08-15 14:48:53.502036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bff0ee5acf3'
down_revision: Union[str, Sequence[str], None] = '1953f2994a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('resend_api_key', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('resend_from_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'resend_from_address')
    op.drop_column('projects', 'resend_api_key')
    # ### end Alembic commands ###
