"""Move mail config to project

Revision ID: 2837a5ad8492
Revises: c7e18cc0d730
Create Date: 2026-08-09 16:38:56.177236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2837a5ad8492'
down_revision: Union[str, Sequence[str], None] = 'c7e18cc0d730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'zeptomail_from_address')
    op.drop_column('admins', 'zeptomail_api_key')
    op.drop_column('admins', 'mail_provider')
    op.add_column('projects', sa.Column('mail_provider', sa.String(), nullable=False))
    op.add_column('projects', sa.Column('zeptomail_api_key', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('zeptomail_from_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'zeptomail_from_address')
    op.drop_column('projects', 'zeptomail_api_key')
    op.drop_column('projects', 'mail_provider')
    op.add_column('admins', sa.Column('mail_provider', sa.VARCHAR(), server_default=sa.text("'console'::character varying"), autoincrement=False, nullable=False))
    op.add_column('admins', sa.Column('zeptomail_api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('admins', sa.Column('zeptomail_from_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
