"""add_last_signed_in

Revision ID: 39ee1a25f26c
Revises: 0c2cdbbf19d0
Create Date: 2026-08-08 21:54:47.388614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ee1a25f26c'
down_revision: Union[str, Sequence[str], None] = '0c2cdbbf19d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_signed_in', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_signed_in')
    # ### end Alembic commands ###
