"""Add user_metadata column

Revision ID: 3e13d829960a
Revises: f0a3bb8eff6b
Create Date: 2026-08-16 21:30:21.087914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e13d829960a'
down_revision: Union[str, Sequence[str], None] = 'f0a3bb8eff6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_metadata', sa.JSON(), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_metadata')
    # ### end Alembic commands ###
