"""add_admin_mail_provider

Revision ID: 435ce765df6c
Revises: 522fb75193c9
Create Date: 2026-08-08 23:29:46.695693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435ce765df6c'
down_revision: Union[str, Sequence[str], None] = '522fb75193c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('mail_provider', sa.String(), server_default='console', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'mail_provider')
    # ### end Alembic commands ###
