"""add_admin_zeptomail_settings

Revision ID: 522fb75193c9
Revises: dcd24af3faae
Create Date: 2026-08-08 23:04:05.366583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522fb75193c9'
down_revision: Union[str, Sequence[str], None] = 'dcd24af3faae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('zeptomail_api_key', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('zeptomail_from_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'zeptomail_from_address')
    op.drop_column('admins', 'zeptomail_api_key')
    # ### end Alembic commands ###
