"""add_developers

Revision ID: c7e18cc0d730
Revises: 435ce765df6c
Create Date: 2026-08-09 16:04:51.763552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e18cc0d730'
down_revision: Union[str, Sequence[str], None] = '435ce765df6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developers_email'), 'developers', ['email'], unique=True)
    op.create_index(op.f('ix_developers_id'), 'developers', ['id'], unique=False)
    
    # 1. Add developer_id as nullable
    op.add_column('projects', sa.Column('developer_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('allowed_origins', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'projects', 'developers', ['developer_id'], ['id'])
    
    # 2. Insert a default developer
    op.execute("INSERT INTO developers (email, hashed_password) VALUES ('default_dev@example.com', 'default_hash')")
    
    # 3. Update existing projects to belong to the default developer (ID 1)
    op.execute("UPDATE projects SET developer_id = 1 WHERE developer_id IS NULL")
    
    # 4. Alter column to be non-nullable
    op.alter_column('projects', 'developer_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'allowed_origins')
    op.drop_column('projects', 'developer_id')
    op.drop_index(op.f('ix_developers_id'), table_name='developers')
    op.drop_index(op.f('ix_developers_email'), table_name='developers')
    op.drop_table('developers')
    # ### end Alembic commands ###
