"""Add allow_public_registration to projects

Revision ID: d99870243f33
Revises: a68efc680a9e
Create Date: 2026-08-15 22:57:27.679462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99870243f33'
down_revision: Union[str, Sequence[str], None] = 'a68efc680a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('allow_public_registration', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'allow_public_registration')
    # ### end Alembic commands ###
