"""enterprise mail config refactor

Revision ID: eb7e46092b9f
Revises: 0bff0ee5acf3
Create Date: 2026-08-15 14:55:07.606732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7e46092b9f'
down_revision: Union[str, Sequence[str], None] = '0bff0ee5acf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('mail_config', sa.JSON(), nullable=True))
    op.drop_column('projects', 'mail_provider')
    op.drop_column('projects', 'zeptomail_api_key')
    op.drop_column('projects', 'resend_from_address')
    op.drop_column('projects', 'resend_api_key')
    op.drop_column('projects', 'zeptomail_from_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('zeptomail_from_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('resend_api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('resend_from_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('zeptomail_api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('mail_provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('projects', 'mail_config')
    # ### end Alembic commands ###
